parser: '@typescript-eslint/parser'

extends:
  - prettier

plugins:
  - prettier

rules:
  prettier/prettier:
    - error
    - endOfLine: auto

  import/no-extraneous-dependencies:
    - off

env:
  browser: true
  jest: true
